---
abstract: 'disconnect all databases'
author:
  - 'Masahiro Nagano E<lt>kazeburo AAJKLFJEF@ gmail.comE<gt>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-DisconnectAll
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  DBIx::DisconnectAll:
    file: lib/DBIx/DisconnectAll.pm
    version: 0.03
requires:
  DBD::SQLite: 1.33
  DBI: 1.604
  parent: 0
  perl: 5.008005
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
